# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

**1. Import the numpy package under the name `np` (★☆☆)**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration (★☆☆)**

In [2]:
print(f'numpy version: {np.__version__}\n')
print(np.show_config())

numpy version: 1.21.5

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NelsonLage/anaconda3\\Library\

**3. Create a null vector of size 10 (★☆☆)**

In [3]:
array0 = np.zeros(10)
array0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array (★☆☆)**

In [4]:
# array.size: how many items in an array
# array.itemsize: memory size of an item in the array

memory_size_array = array0.size * array0.itemsize
memory_size_array

80

**5. How to get the documentation of the numpy add function from the command line? (★☆☆)**

In [5]:
# np.info('add')

**6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**

In [6]:
array0[4] = 1
array0

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49 (★☆☆)**

In [7]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8. Reverse a vector (first element becomes last) (★☆☆)**

In [8]:
array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)**

In [9]:
arr_3 = np.arange(0,9).reshape(3, 3)
arr_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)**

In [10]:
# np.nonzero returns a tuple with a single element.
# To access the list of indices: np.nonzero(array)[0]

array = [1,2,0,0,4,0]
np.nonzero(array)

(array([0, 1, 4], dtype=int64),)

**11. Create a 3x3 identity matrix (★☆☆)**

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12. Create a 3x3x3 array with random values (★☆☆)**

In [12]:
np.random.seed(0)

np.random.random(size=(3,3,3))

array([[[0.5488135 , 0.71518937, 0.60276338],
        [0.54488318, 0.4236548 , 0.64589411],
        [0.43758721, 0.891773  , 0.96366276]],

       [[0.38344152, 0.79172504, 0.52889492],
        [0.56804456, 0.92559664, 0.07103606],
        [0.0871293 , 0.0202184 , 0.83261985]],

       [[0.77815675, 0.87001215, 0.97861834],
        [0.79915856, 0.46147936, 0.78052918],
        [0.11827443, 0.63992102, 0.14335329]]])

**13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)**

In [13]:
np.random.seed(0)

array10 = np.random.random(size=(10,10))
array10_min = np.min(array10)
array10_max = np.max(array10)

print(array10)
print(f'\nMin value: {array10_min}')
print(f'Max value: {array10_max}')

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
  0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
  0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672 0.67063787
  0.21038256 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 0.10204481 0.20887676 0.16130952
  0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
  0.82099323 0.09710128 0.83794491 0.09609841]
 [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358 0.03918779
  0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145 0.26538949
  0.52324805 0

**14. Create a random vector of size 30 and find the mean value (★☆☆)**

In [14]:
np.random.seed(0)

array30 = np.random.random(size=(30))
array_mean = np.mean(array30)

print(f'{array30}\n')
print(f'Mean: {array_mean}')

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]

Mean: 0.5811203282945502


**15. Create a 2d array with 1 on the border and 0 inside (★☆☆)**

In [15]:
array = np.ones((3,3))
array[1:-1, 1:-1] = 0
array

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

**16. How to add a border (filled with 0's) around an existing array? (★☆☆)**

In [16]:
np.pad(array, 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

**17. What is the result of the following expression? (★☆☆)**
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
# Arithmetic operations propagate the nan values
print(0 * np.nan)
print(np.nan - np.nan)

# np.nan is unordered with respect to any other number (itself included).
# The following are always False
print(np.nan == np.nan)
print(np.inf > np.nan)

# Rounding involved in the right hand side operation makes it False
print(0.3 == 3 * 0.1)

print(np.nan in set([np.nan]))

nan
nan
False
False
False
True


**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)**

In [18]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)**

In [19]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)**

In [20]:
# numpy.unravel_index(indices, shape, order='C')
# indices of the desired elements in a flattened array
  # the 100th element has index 99!
# order: style of the indices - 'C' for row-major, 'F' for column-major

np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

In [21]:
# cheking the answer
# np.arange(336).reshape(6,7,8)

**21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)**

In [22]:
array = np.array([[1, 0], [0, 1]])

Z = np.tile(array, (4, 4))
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**22. Normalize a 5x5 random matrix (★☆☆)**

In [23]:
np.random.seed(0)
array = np.random.random(size=(5,5))
array

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

In [24]:
normalized_array = (array - np.mean(array)) / np.std(array)
normalized_array

array([[-0.14854421,  0.44055117,  0.04247881, -0.1624605 , -0.59169993],
       [ 0.19519398, -0.54236874,  1.06578972,  1.32033341, -0.73408512],
       [ 0.71154487, -0.21907095, -0.08045184,  1.18555078, -1.84023484],
       [-1.78325269, -2.02016749,  0.85634317,  0.66350295,  0.98873998],
       [ 1.37328739,  0.73786513, -0.4577726 ,  0.67190312, -1.67297558]])

**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)**

In [25]:
# no idea

**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)**

In [26]:
np.random.seed(0)

arr_1 = np.random.random(size=(5,3))
arr_2 = np.random.random(size=(3,3))

print(f'{arr_1}\n')
print(f'{arr_2}')

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]

[[0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]]


In [27]:
arr_1.dot(arr_2)

array([[1.08605068, 0.91148242, 1.62732485],
       [0.89331694, 0.67766829, 1.37241611],
       [1.5021852 , 1.22941113, 1.98921611],
       [1.07216608, 0.94063706, 1.50687558],
       [0.82652167, 0.84954695, 1.43421674]])

**25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)**

In [28]:
a = np.arange(10)
a[(a < 3) | (a > 8)]

array([0, 1, 2, 9])

## Optional

**26. What is the output of the following script? (★☆☆)**
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

When you import the functions of a library instead of the library itself, they can overwrite built-in fuctions with the same name. <br>
In the script, `np.sum` takes the place of the built-in function `sum` and they behave differently.

In [29]:
# Here -1 is just another element
sum(range(5), -1)

9

In [30]:
# Here -1 is interpreted as the axis parameter. If negative, counts from the last to the first axis.
np.sum(range(5), -1)

10

**27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)**
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
Z = np.array(2)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

4
2
False
2j
2.0
False


**28. What are the result of the following expressions? (★☆☆)**
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

**29. How to round away from zero a float array ? (★☆☆)**

**30. How to find common values between two arrays? (★☆☆)**

**31. How to ignore all numpy warnings (not recommended)? (★☆☆)**

**32. Is the following expressions true? (★☆☆)**
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

**33. How to get the dates of yesterday, today and tomorrow? (★☆☆)**

**34. How to get all the dates corresponding to the month of July 2016? (★★☆)**

**35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)**

**36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)**

**37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)**

**38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)**

**39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)**

**40. Create a random vector of size 10 and sort it (★★☆)**

**41. How to sum a small array faster than np.sum? (★★☆)**

**42. Consider two random array A and B, check if they are equal (★★☆)**

**43. Make an array immutable (read-only) (★★☆)**

**44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)**

**45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)**

**46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)**

**47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)**

**48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)**

**49. How to print all the values of an array? (★★☆)**

**50. How to find the closest value (to a given scalar) in a vector? (★★☆)**

**51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)**

**52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)**

**53. How to convert a float (32 bits) array into an integer (32 bits) in place?**

**54. How to read the following file? (★★☆)**
```python
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

**55. What is the equivalent of enumerate for numpy arrays? (★★☆)**

**56. Generate a generic 2D Gaussian-like array (★★☆)**

**57. How to randomly place p elements in a 2D array? (★★☆)**

**58. Subtract the mean of each row of a matrix (★★☆)**

**59. How to sort an array by the nth column? (★★☆)**

**60. How to tell if a given 2D array has null columns? (★★☆)**

**61. Find the nearest value from a given value in an array (★★☆)**

**62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)**

**63. Create an array class that has a name attribute (★★☆)**

**64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)**

**65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)**

**66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)**

**67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)**

**68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)**

**69. How to get the diagonal of a dot product? (★★★)**

**70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)**

**71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)**

**72. How to swap two rows of an array? (★★★)**

**73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)**

**74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)**

**75. How to compute averages using a sliding window over an array? (★★★)**

**76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)**

**77. How to negate a boolean, or to change the sign of a float inplace? (★★★)**

**78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)**

**79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)**

**80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)**

**81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)**

**82. Compute a matrix rank (★★★)**

**83. How to find the most frequent value in an array?**

**84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)**

**85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)**

**86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)**

**87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)**

**88. How to implement the Game of Life using numpy arrays? (★★★)**

**89. How to get the n largest values of an array (★★★)**

**90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)**

**91. How to create a record array from a regular array? (★★★)**

**92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)**

**93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)**

**94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)**

**95. Convert a vector of ints into a matrix binary representation (★★★)**

**96. Given a two dimensional array, how to extract unique rows? (★★★)**

**97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)**

**98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?**

**99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)**

**100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)**